#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# DELL
# xrandr --output DFP10 --primary
# SAMSUNG
# xrandr --output DFP11 --primary

# exec gnome-session
# exec startkde
# exec startxfce4
# ...or the Window Manager of your choice
case $1 in
  xmonad)
    exec xmonad
    ;;
  *)
    exec startxfce4
    ;;
esac

exit 0
